"""phase2_corp_alliance_bucket_apitoken_sde

Revision ID: e9bb4834a3e7
Revises: 0ae7658bbb38
Create Date: 2026-04-27 15:34:00.685756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bb4834a3e7'
down_revision: Union[str, Sequence[str], None] = '0ae7658bbb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('creator_corp_id', sa.BigInteger(), nullable=True),
    sa.Column('executor_corp_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alliances_alliance_id'), 'alliances', ['alliance_id'], unique=True)
    op.create_table('buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corporations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('ceo_id', sa.BigInteger(), nullable=True),
    sa.Column('alliance_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporations_corporation_id'), 'corporations', ['corporation_id'], unique=True)
    op.create_table('sde_type_info',
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sde_type_info_name'), 'sde_type_info', ['name'], unique=False)
    op.create_table('alliance_corporations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alliance_id', 'corporation_id', name='uq_alliance_corp')
    )
    op.create_index(op.f('ix_alliance_corporations_alliance_id'), 'alliance_corporations', ['alliance_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('corporation_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'item_id', name='uq_corp_asset')
    )
    op.create_index(op.f('ix_corporation_assets_corporation_id'), 'corporation_assets', ['corporation_id'], unique=False)
    op.create_table('corporation_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('ship_type_id', sa.Integer(), nullable=True),
    sa.Column('ship_type_name', sa.String(length=256), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logon_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logoff_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'character_id', name='uq_corp_member')
    )
    op.create_index(op.f('ix_corporation_members_corporation_id'), 'corporation_members', ['corporation_id'], unique=False)
    op.create_table('corporation_wallet_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_type', sa.String(length=128), nullable=False),
    sa.Column('first_party_id', sa.BigInteger(), nullable=True),
    sa.Column('second_party_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'division', 'journal_id', name='uq_corp_wallet_journal')
    )
    op.create_index(op.f('ix_corporation_wallet_journals_corporation_id'), 'corporation_wallet_journals', ['corporation_id'], unique=False)
    op.create_table('corporation_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('wallet_division', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'wallet_division', name='uq_corp_wallet_div')
    )
    op.create_index(op.f('ix_corporation_wallets_corporation_id'), 'corporation_wallets', ['corporation_id'], unique=False)
    op.create_table('bucket_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_id', 'character_id', name='uq_bucket_character')
    )
    op.create_index(op.f('ix_bucket_tokens_bucket_id'), 'bucket_tokens', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_bucket_tokens_character_id'), 'bucket_tokens', ['character_id'], unique=False)
    op.create_table('character_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_type', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'notification_id', name='uq_char_notification')
    )
    op.create_index(op.f('ix_character_notifications_character_id'), 'character_notifications', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_notifications_timestamp'), 'character_notifications', ['timestamp'], unique=False)
    op.create_table('character_skill_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('finished_level', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_start_sp', sa.BigInteger(), nullable=True),
    sa.Column('level_start_sp', sa.BigInteger(), nullable=True),
    sa.Column('level_end_sp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'queue_position', name='uq_char_skill_queue_pos')
    )
    op.create_index(op.f('ix_character_skill_queues_character_id'), 'character_skill_queues', ['character_id'], unique=False)
    op.create_table('character_wallet_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_type', sa.String(length=128), nullable=False),
    sa.Column('first_party_id', sa.BigInteger(), nullable=True),
    sa.Column('second_party_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context_id', sa.BigInteger(), nullable=True),
    sa.Column('context_id_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'journal_id', name='uq_char_wallet_journal')
    )
    op.create_index(op.f('ix_character_wallet_journals_character_id'), 'character_wallet_journals', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_wallet_journals_date'), 'character_wallet_journals', ['date'], unique=False)
    op.create_table('character_wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('is_buy', sa.Boolean(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('journal_ref_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'transaction_id', name='uq_char_wallet_tx')
    )
    op.create_index(op.f('ix_character_wallet_transactions_character_id'), 'character_wallet_transactions', ['character_id'], unique=False)
    op.add_column('characters', sa.Column('corporation_db_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'corporations', ['corporation_db_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'corporation_db_id')
    op.drop_index(op.f('ix_character_wallet_transactions_character_id'), table_name='character_wallet_transactions')
    op.drop_table('character_wallet_transactions')
    op.drop_index(op.f('ix_character_wallet_journals_date'), table_name='character_wallet_journals')
    op.drop_index(op.f('ix_character_wallet_journals_character_id'), table_name='character_wallet_journals')
    op.drop_table('character_wallet_journals')
    op.drop_index(op.f('ix_character_skill_queues_character_id'), table_name='character_skill_queues')
    op.drop_table('character_skill_queues')
    op.drop_index(op.f('ix_character_notifications_timestamp'), table_name='character_notifications')
    op.drop_index(op.f('ix_character_notifications_character_id'), table_name='character_notifications')
    op.drop_table('character_notifications')
    op.drop_index(op.f('ix_bucket_tokens_character_id'), table_name='bucket_tokens')
    op.drop_index(op.f('ix_bucket_tokens_bucket_id'), table_name='bucket_tokens')
    op.drop_table('bucket_tokens')
    op.drop_index(op.f('ix_corporation_wallets_corporation_id'), table_name='corporation_wallets')
    op.drop_table('corporation_wallets')
    op.drop_index(op.f('ix_corporation_wallet_journals_corporation_id'), table_name='corporation_wallet_journals')
    op.drop_table('corporation_wallet_journals')
    op.drop_index(op.f('ix_corporation_members_corporation_id'), table_name='corporation_members')
    op.drop_table('corporation_members')
    op.drop_index(op.f('ix_corporation_assets_corporation_id'), table_name='corporation_assets')
    op.drop_table('corporation_assets')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_alliance_corporations_alliance_id'), table_name='alliance_corporations')
    op.drop_table('alliance_corporations')
    op.drop_index(op.f('ix_sde_type_info_name'), table_name='sde_type_info')
    op.drop_table('sde_type_info')
    op.drop_index(op.f('ix_corporations_corporation_id'), table_name='corporations')
    op.drop_table('corporations')
    op.drop_table('buckets')
    op.drop_index(op.f('ix_alliances_alliance_id'), table_name='alliances')
    op.drop_table('alliances')
    # ### end Alembic commands ###
