"""sde_create_type_group_category

Revision ID: f4fe5a7e15dd
Revises: e9bb4834a3e7
Create Date: 2026-04-27 23:44:18.915581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4fe5a7e15dd'
down_revision: Union[str, Sequence[str], None] = 'e9bb4834a3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('sde_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_sde_group_category_id'), 'sde_group', ['category_id'], unique=False)
    op.create_table('sde_type',
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sde_type_category_id'), 'sde_type', ['category_id'], unique=False)
    op.create_index(op.f('ix_sde_type_group_id'), 'sde_type', ['group_id'], unique=False)
    op.drop_index(op.f('ix_sde_type_info_name'), table_name='sde_type_info')
    op.drop_table('sde_type_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_type_info',
    sa.Column('type_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mass', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('type_id', name=op.f('sde_type_info_pkey'))
    )
    op.create_index(op.f('ix_sde_type_info_name'), 'sde_type_info', ['name'], unique=False)
    op.drop_index(op.f('ix_sde_type_group_id'), table_name='sde_type')
    op.drop_index(op.f('ix_sde_type_category_id'), table_name='sde_type')
    op.drop_table('sde_type')
    op.drop_index(op.f('ix_sde_group_category_id'), table_name='sde_group')
    op.drop_table('sde_group')
    op.drop_table('sde_category')
    # ### end Alembic commands ###
